services:
  pharmavillage_io:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"